-- Add remaining official D&D 5e backgrounds from Player's Handbook
-- Current database only has 5 backgrounds, but PHB contains 13 total

-- Charlatan
INSERT OR REPLACE INTO backgrounds (id, name, skill_proficiencies, language_proficiencies, tool_proficiencies, equipment, feature_name, feature_description, personality_traits, ideals, bonds, flaws, source) VALUES
('charlatan', 'Charlatan', '["Deception", "Sleight of Hand"]', '[]', '["Forgery kit", "One type of gaming set"]', '{"items": ["set of fine clothes", "disguise kit", "tools of the con of your choice", "belt pouch"], "money": "15 gp"}', 'False Identity', 'You have created a second identity that includes documentation, established acquaintances, and disguises.', '["I fall in and out of love easily", "I have a joke for every occasion", "Flattery is my preferred trick for getting what I want", "I''m a born gambler who can''t resist taking a risk"]', '["Independence", "Fairness", "Charity", "Creativity", "Friendship", "Aspiration"]', '["I fleeced the wrong person and must work to ensure that this individual never crosses paths with me", "I owe everything to my mentor", "Somewhere out there, I have a child who doesn''t know me", "I come from a noble family, and one day I''ll reclaim my lands"]', '["I can''t resist a pretty face", "I''m always in debt", "I''m convinced that no one could ever fool me the way I fool others", "I''m too greedy for my own good"]', 'PHB'),

-- Entertainer
('entertainer', 'Entertainer', '["Acrobatics", "Performance"]', '[]', '["Disguise kit", "One type of musical instrument"]', '{"items": ["musical instrument", "favor of an admirer", "costume", "belt pouch"], "money": "15 gp"}', 'By Popular Demand', 'You can always find a place to perform, usually in an inn or tavern but possibly with a circus, at a theater, or even in a noble''s court.', '["I know a story relevant to almost every situation", "Whenever I come to a new place, I collect local rumors and spread gossip", "I''m a hopeless romantic", "Nobody stays angry at me or around me for long"]', '["Beauty", "Tradition", "Creativity", "Greed", "People", "Honesty"]', '["My instrument is my most treasured possession", "Someone stole my precious instrument", "I want to be famous, whatever it takes", "I idolize a hero of the old tales"]', '["I''ll do anything to win fame and renown", "I''m a sucker for a pretty face", "A scandal prevents me from ever going home again", "I once satirized a noble who still wants my head"]', 'PHB'),

-- Guild Artisan
('guild-artisan', 'Guild Artisan', '["Insight", "Persuasion"]', '["One of your choice"]', '["One type of artisan tools"]', '{"items": ["set of artisan tools", "letter of introduction from your guild", "traveler''s clothes", "belt pouch"], "money": "15 gp"}', 'Guild Membership', 'As an established and respected member of a guild, you can rely on certain benefits that membership provides.', '["I believe that anything worth doing is worth doing right", "I''m a snob who looks down on those who can''t appreciate fine art", "I always want to know how things work", "I''m full of witty aphorisms and have a proverb for every occasion"]', '["Community", "Generosity", "Freedom", "Greed", "People", "Aspiration"]', '["The workshop where I learned my trade is the most important place in the world to me", "I created a great work for someone, and then found them unworthy to receive it", "I owe my guild a great debt for forging me into the person I am today", "I pursue wealth to secure someone''s love"]', '["I''ll do anything to get my hands on something rare or priceless", "I''m quick to assume that someone is trying to cheat me", "No one must ever learn that I once stole money from guild coffers", "I''m never satisfied with what I have"]', 'PHB'),

-- Hermit
('hermit', 'Hermit', '["Medicine", "Religion"]', '["One of your choice"]', '["Herbalism kit"]', '{"items": ["herbalism kit", "scroll case stuffed full of notes", "winter blanket", "set of common clothes", "belt pouch"], "money": "5 gp"}', 'Discovery', 'The quiet seclusion of your extended hermitage gave you access to a unique and powerful discovery.', '["I''ve been isolated for so long that I rarely speak", "I am utterly serene, even in the face of disaster", "The leader of my community had something wise to say on every topic", "I connect everything that happens to me to a grand, cosmic plan"]', '["Greater Good", "Logic", "Free Thinking", "Power", "Live and Let Live", "Self-Knowledge"]', '["Nothing is more important than the other members of my hermitage", "I entered seclusion to hide from the ones who might still be hunting me", "I''m still seeking the enlightenment I pursued in my seclusion", "I entered seclusion because I loved someone I could not have"]', '["Now that I''ve returned to the world, I enjoy its delights a little too much", "I harbor dark, bloodthirsty thoughts that my isolation failed to quell", "I am dogmatic in my thinking and philosophy", "I let my need to win arguments overshadow friendships"]', 'PHB'),

-- Outlander
('outlander', 'Outlander', '["Athletics", "Survival"]', '["One of your choice"]', '["One type of musical instrument"]', '{"items": ["staff", "hunting trap", "traveler''s clothes", "belt pouch"], "money": "10 gp"}', 'Wanderer', 'You have an excellent memory for maps and geography, and you can always recall the general layout of terrain, settlements, and other features around you.', '["I''m driven by a wanderlust that led me away from home", "I watch over my friends as if they were a litter of newborn pups", "I once ran twenty-five miles without stopping to warn to my clan of an approaching orc horde", "I have a lesson for every situation, drawn from observing nature"]', '["Change", "Greater Good", "Honor", "Might", "Nature", "Glory"]', '["My family, clan, or tribe is the most important thing in my life", "An injury to the unspoiled wilderness of my home is an injury to me", "I will bring terrible wrath down on the evildoers who destroyed my homeland", "I am the last of my tribe"]', '["I am too enamored of ale, wine, and other intoxicants", "There''s no room for caution in a life lived to the fullest", "I remember every insult I''ve received and nurse a silent resentment toward anyone who''s ever wronged me", "I am slow to trust members of other races, tribes, and societies"]', 'PHB'),

-- Sailor
('sailor', 'Sailor', '["Athletics", "Perception"]', '[]', '["Navigator''s tools", "Vehicles (water)"]', '{"items": ["belaying pin (club)", "silk rope (50 feet)", "lucky charm", "common clothes", "belt pouch"], "money": "10 gp"}', 'Ship''s Passage', 'When you need to, you can secure free passage on a sailing ship for yourself and your adventuring companions.', '["My friends know they can rely on me, no matter what", "I work hard so that I can play hard when the work is done", "I enjoy sailing into new ports and making new friends over a flagon of ale", "I stretch the truth for the sake of a good story"]', '["Respect", "Fairness", "Freedom", "Mastery", "People", "Aspiration"]', '["I''m loyal to my captain first, everything else second", "The ship is most important—crewmates and captains come and go", "I''ll always remember my first ship", "In a harbor town, I have a paramour whose eyes nearly stole me from the sea"]', '["I follow orders, even if I think they''re wrong", "I''ll say anything to avoid having to do extra work", "Once someone questions my courage, I never back down no matter how dangerous the situation", "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life"]', 'PHB'),

-- Soldier
('soldier', 'Soldier', '["Athletics", "Intimidation"]', '[]', '["One type of gaming set", "Vehicles (land)"]', '{"items": ["insignia of rank", "trophy taken from fallen enemy", "deck of cards", "common clothes", "belt pouch"], "money": "10 gp"}', 'Military Rank', 'You have a military rank from your career as a soldier. Soldiers loyal to your former military organization still recognize your authority and influence.', '["I''m always polite and respectful", "I''m haunted by memories of war", "I''ve lost too many friends, and I''m slow to make new ones", "I''m full of inspiring and cautionary tales from my military experience"]', '["Greater Good", "Responsibility", "Independence", "Might", "Live and Let Live", "Nation"]', '["I would still lay down my life for the people I served with", "Someone saved my life on the battlefield", "My honor is my life", "I''ll never forget the crushing defeat my company suffered"]', '["The monstrous enemy we faced in battle still leaves me quivering with fear", "I have little respect for anyone who is not a proven warrior", "I made a terrible mistake in battle that cost many lives", "My hatred of my enemies is blind and unreasoning"]', 'PHB'),

-- Urchin
('urchin', 'Urchin', '["Sleight of Hand", "Stealth"]', '[]', '["Disguise kit", "Thieves'' tools"]', '{"items": ["small knife", "map of the city you grew up in", "pet mouse", "token to remember your parents", "common clothes", "belt pouch"], "money": "10 gp"}', 'City Secrets', 'You know the secret patterns and flow to cities and can find passages through the urban sprawl that others would miss.', '["I hide scraps of food and trinkets away in my pockets", "I ask a lot of questions", "I like to squeeze into small places where no one else can get to me", "I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms"]', '["Respect", "Community", "Change", "Retribution", "People", "Aspiration"]', '["My town or city is my home, and I''ll fight to defend it", "I sponsor an orphanage to keep others from enduring what I was forced to endure", "I owe my survival to another urchin who taught me to live on the streets", "I owe a debt I can never repay to the person who took pity on me"]', '["If I''m outnumbered, I will run away from a fight", "Gold seems like a lot of money to me, and I''ll do just about anything for more of it", "I will never fully trust anyone other than myself", "I''d rather kill someone in their sleep than fight fair"]', 'PHB');