-- Add backgrounds from Sword Coast Adventurer's Guide (SCAG)
-- These backgrounds are specific to the Forgotten Realms setting

INSERT OR REPLACE INTO backgrounds (id, name, skill_proficiencies, language_proficiencies, tool_proficiencies, equipment, feature_name, feature_description, personality_traits, ideals, bonds, flaws, source) VALUES

-- City Watch / Investigator
('city-watch', 'City Watch', '["Athletics", "Insight"]', '["Two of your choice"]', '[]', '{"items": ["uniform in the style of your unit", "insignia of your rank", "horn", "set of manacles", "belt pouch"], "money": "10 gp"}', 'Watcher''s Eye', 'Your experience in enforcing the law gives you a feel for local laws and criminals. You can easily find the local outposts of the watch or similar organizations.', '["I''m always polite and respectful", "I''m haunted by memories of war", "I''ve lost too many friends, and I''m slow to make new ones", "I''m full of inspiring and cautionary tales from my military experience"]', '["Greater Good", "Responsibility", "Independence", "Might", "Live and Let Live", "Nation"]', '["I would still lay down my life for the people I served with", "Someone saved my life on the battlefield", "My honor is my life", "I''ll never forget the crushing defeat my company suffered"]', '["The monstrous enemy we faced in battle still leaves me quivering with fear", "I have little respect for anyone who is not a proven warrior", "I made a terrible mistake in battle that cost many lives", "My hatred of my enemies is blind and unreasoning"]', 'SCAG'),

-- Clan Crafter
('clan-crafter', 'Clan Crafter', '["History", "Insight"]', '["Dwarvish or one other if you already speak Dwarvish"]', '["One type of artisan tools"]', '{"items": ["set of artisan tools", "maker''s mark chisel", "set of traveler''s clothes", "belt pouch"], "money": "5 gp"}', 'Respect of the Stout Folk', 'As well respected as clan crafters are among outsiders, no one esteems them quite so highly as dwarves do. You always have free room and board in any place where shield dwarves or gold dwarves dwell.', '["I believe that anything worth doing is worth doing right", "I''m a snob who looks down on those who can''t appreciate fine art", "I always want to know how things work", "I''m full of witty aphorisms and have a proverb for every occasion"]', '["Community", "Generosity", "Freedom", "Greed", "People", "Aspiration"]', '["The workshop where I learned my trade is the most important place in the world to me", "I created a great work for someone, and then found them unworthy to receive it", "I owe my guild a great debt for forging me into the person I am today", "I pursue wealth to secure someone''s love"]', '["I''ll do anything to get my hands on something rare or priceless", "I''m quick to assume that someone is trying to cheat me", "No one must ever learn that I once stole money from guild coffers", "I''m never satisfied with what I have"]', 'SCAG'),

-- Cloistered Scholar
('cloistered-scholar', 'Cloistered Scholar', '["History", "Arcana"]', '["Two of your choice"]', '[]', '{"items": ["ink and quill", "small knife", "letter from a dead colleague", "set of common clothes", "belt pouch"], "money": "10 gp"}', 'Library Access', 'Though others must often endure extensive interviews and significant fees to gain access to even the most common archives in your library, you have free and easy access to the majority of the library.', '["I use polysyllabic words that convey the impression of great erudition", "I''ve read every book in the world''s greatest libraries—or I like to boast that I have", "I''m used to helping out those who aren''t as smart as I am", "There''s nothing I like more than a good mystery"]', '["Knowledge", "Beauty", "Logic", "No Limits", "Self-Improvement", "Power"]', '["It is my duty to protect my students", "I have an ancient text that holds terrible secrets", "I work to preserve a library, university, scriptorium, or monastery", "My life''s work is a series of tomes related to a specific field of lore"]', '["I am easily distracted by the promise of information", "Most people scream and run when they see a demon. I stop and take notes", "Unlocking an ancient mystery is worth the price of a civilization", "I overlook obvious solutions in favor of complicated ones"]', 'SCAG'),

-- Courtier
('courtier', 'Courtier', '["Insight", "Persuasion"]', '["Two of your choice"]', '[]', '{"items": ["set of fine clothes", "signet ring", "scroll of pedigree", "purse"], "money": "5 gp"}', 'Court Functionary', 'Your knowledge of how bureaucracies function lets you gain access to the records and inner workings of any noble court or government you encounter.', '["I flattery is my preferred trick for getting what I want", "I''m a born gambler who can''t resist taking a risk for a potential payoff", "I lie about almost everything, even when there''s no good reason to", "Sarcasm and insults are my weapons of choice"]', '["Respect", "Responsibility", "Independence", "Power", "Freedom", "Noble Obligation"]', '["I will face any challenge to win the approval of my family", "My house''s alliance with another noble family must be sustained at all costs", "Nothing is more important than the other members of my family", "I am in love with the heir of a family that my family despises"]', '["I secretly believe that everyone is beneath me", "I hide a truly scandalous secret that would ruin my family forever", "I too often hear veiled insults and threats where none exist", "I have an insatiable desire for carnal pleasures"]', 'SCAG'),

-- Faction Agent
('faction-agent', 'Faction Agent', '["Insight", "one Intelligence, Wisdom, or Charisma skill"]', '["Two of your choice"]', '[]', '{"items": ["badge or emblem of your faction", "copy of a seminal faction text", "set of common clothes", "belt pouch"], "money": "15 gp"}', 'Safe Haven', 'As a faction agent, you have access to a secret network of supporters and operatives who can provide assistance on your adventures.', '["I idolize a particular hero of my faith", "I can find common ground between the fiercest enemies", "I see omens in every event and action", "Nothing can shake my optimistic attitude"]', '["Tradition", "Charity", "Change", "Power", "Faith", "Aspiration"]', '["I would die to recover an ancient relic of my faith that was lost long ago", "I will someday get revenge on the corrupt temple hierarchy", "I owe my life to the priest who took me in when my parents died", "I fight for those who cannot fight for themselves"]', '["I judge others harshly, and myself even more severely", "I put too much trust in those who wield power within my temple''s hierarchy", "My piety sometimes leads me to blindly trust those that profess faith in my god", "I am inflexible in my thinking"]', 'SCAG'),

-- Far Traveler
('far-traveler', 'Far Traveler', '["Insight", "Perception"]', '["One of your choice"]', '["One musical instrument or gaming set"]', '{"items": ["set of traveler''s clothes", "jewelry worth 10 gp", "poorly wrought maps", "small piece of jewelry worth 10 gp"], "money": "5 gp"}', 'All Eyes on You', 'Your accent, mannerisms, figures of speech, and perhaps even your appearance all mark you as foreign. Curious glances are directed your way wherever you go.', '["I have different assumptions from those around me concerning personal space", "I have my own ideas about what is and is not food", "I have a strong code of honor or sense of propriety that others don''t comprehend", "I express affection or contempt in ways that are unfamiliar to others"]', '["Open", "Punctual", "Inquisitive", "Tolerant", "Suspicious", "Confident"]', '["So long as I have this token from my homeland, I can face any adversity", "The gods of my people are a comfort to me so far from home", "I hold no greater cause than my service to my people", "My freedom is my most precious possession"]', '["I am secretly (or not so secretly) convinced of the superiority of my own culture", "I pretend not to understand the local language", "I have a weakness for the new intoxicants and other pleasures of this land", "I don''t take kindly to some of the actions and motivations of the people"]', 'SCAG'),

-- Inheritor
('inheritor', 'Inheritor', '["Survival", "choice of Arcana, History, or Religion"]', '["One of your choice"]', '["One type of gaming set or musical instrument"]', '{"items": ["your inheritance", "set of traveler''s clothes", "belt pouch"], "money": "15 gp"}', 'Inheritance', 'Choose or randomly determine your inheritance. Work with your Dungeon Master to come up with details: Why is your inheritance so important, and what is its significance?', '["I don''t run from evil. Evil runs from me", "I like to read and memorize poetry", "I become cantankerous and rude when I haven''t had a meal", "I have an iron stomach and can eat and drink things that would make a goat puke"]', '["Respect", "Fairness", "Freedom", "Strength", "Sincerity", "Destiny"]', '["I have a family, but I have no idea where they are", "I worked the land, I love the land, and I will protect the land", "A proud noble once gave me a horrible beating", "My tools are symbols of my past life"]', '["The tyrant who rules my land will stop at nothing to see me killed", "I''m convinced that powerful enemies are hunting me", "I have a weakness for the vices of the city", "There''s a secret I would do anything to keep the local authorities from discovering"]', 'SCAG'),

-- Knight of the Order
('knight-of-the-order', 'Knight of the Order', '["Persuasion", "choice of Arcana, History, Nature, or Religion"]', '["One of your choice"]', '["One type of gaming set or musical instrument"]', '{"items": ["set of traveler''s clothes", "signet, banner, or seal of your order", "belt pouch"], "money": "10 gp"}', 'Knightly Regard', 'You receive shelter and succor from members of your knightly order and those who are sympathetic to its aims.', '["I have a crude sense of humor", "I face problems head-on", "I pay no attention to the risks in a situation", "The best way to get me to do something is to tell me I can''t do it"]', '["Responsibility", "Justice", "Honor", "Glory", "Noble Sacrifice", "Protection"]', '["I will face any challenge to win the approval of my family", "My loyalty to my sovereign is unwavering", "The common folk must see me as a hero of the people", "I have a secret that could ruin my honor forever"]', '["I have an insatiable desire for carnal pleasures", "I can''t resist a pretty face", "I''m too greedy for my own good", "I can''t resist taking a risk if there''s money involved"]', 'SCAG'),

-- Mercenary Veteran
('mercenary-veteran', 'Mercenary Veteran', '["Athletics", "Persuasion"]', '["One of your choice"]', '["One type of gaming set, vehicles (land)"]', '{"items": ["uniform of your company", "insignia of your rank", "gaming set", "common clothes", "belt pouch"], "money": "10 gp"}', 'Mercenary Life', 'You know the mercenary life as only someone who has lived it can. You are able to identify mercenary companies by their emblems, and you know a little about any such company.', '["I''m always polite and respectful", "I''m haunted by memories of war", "I''ve lost too many friends, and I''m slow to make new ones", "I''m full of inspiring and cautionary tales from my military experience"]', '["Greater Good", "Responsibility", "Independence", "Might", "Live and Let Live", "Nation"]', '["I would still lay down my life for the people I served with", "Someone saved my life on the battlefield", "My honor is my life", "I''ll never forget the crushing defeat my company suffered"]', '["The monstrous enemy we faced in battle still leaves me quivering with fear", "I have little respect for anyone who is not a proven warrior", "I made a terrible mistake in battle that cost many lives", "My hatred of my enemies is blind and unreasoning"]', 'SCAG'),

-- Urban Bounty Hunter
('urban-bounty-hunter', 'Urban Bounty Hunter', '["choice of Deception, Insight, Persuasion, or Stealth", "choice of Deception, Insight, Persuasion, or Stealth"]', '["One of your choice"]', '["choice of one type of gaming set, one musical instrument, or thieves'' tools"]', '{"items": ["set of clothes appropriate to your duties", "belt pouch"], "money": "20 gp"}', 'Ear to the Ground', 'You are in frequent contact with people in the segment of society that your chosen quarries move through. These people might be associated with the criminal underworld.', '["I always have a plan for what to do when things go wrong", "I am incredibly slow to trust. Those who seem the fairest often have the most to hide", "Violence is my answer to almost any challenge", "When I set my mind to something, I follow through no matter what gets in my way"]', '["Justice", "Freedom", "Logic", "Power", "Money", "Redemption"]', '["I''m loyal to my captain first, everything else second", "The ship is most important—crewmates and captains come and go", "I''ll always remember my first ship", "In a harbor town, I have a paramour whose eyes nearly stole me from the sea"]', '["When I see something valuable, I can''t think about anything but how to steal it", "When faced with a choice between money and my friends, I usually choose the money", "If there''s a plan, I''ll forget it. If I don''t forget it, I''ll ignore it", "I have a tell that reveals when I''m lying"]', 'SCAG'),

-- Uthgardt Tribe Member
('uthgardt-tribe-member', 'Uthgardt Tribe Member', '["Athletics", "Survival"]', '["One of your choice"]', '["One type of artisan tools or musical instrument"]', '{"items": ["hunting trap", "totemic token or tattoos marking your loyalty to Uthgar", "set of traveler''s clothes", "belt pouch"], "money": "10 gp"}', 'Uthgardt Heritage', 'You have an excellent knowledge of not only your own tribe''s territory, but also the terrain and natural resources of all the North.', '["I''m driven by a wanderlust that led me away from home", "I watch over my friends as if they were a litter of newborn pups", "I once ran twenty-five miles without stopping to warn to my clan of an approaching orc horde", "I have a lesson for every situation, drawn from observing nature"]', '["Change", "Greater Good", "Honor", "Might", "Nature", "Glory"]', '["My family, clan, or tribe is the most important thing in my life", "An injury to the unspoiled wilderness of my home is an injury to me", "I will bring terrible wrath down on the evildoers who destroyed my homeland", "I am the last of my tribe"]', '["I am too enamored of ale, wine, and other intoxicants", "There''s no room for caution in a life lived to the fullest", "I remember every insult I''ve received and nurse a silent resentment toward anyone who''s ever wronged me", "I am slow to trust members of other races, tribes, and societies"]', 'SCAG'),

-- Waterdhavian Noble
('waterdhavian-noble', 'Waterdhavian Noble', '["History", "Persuasion"]', '["One of your choice"]', '["One type of gaming set or musical instrument"]', '{"items": ["set of fine clothes", "signet ring", "scroll of pedigree", "skin of fine zzar or wine", "purse"], "money": "20 gp"}', 'Kept in Style', 'While you are in Waterdeep or elsewhere in the North your house sees to your everyday needs. Your name and signet are sufficient to cover most of your expenses.', '["My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world", "The common folk love me for my kindness and generosity", "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses", "I take great pains to always look my best and follow the latest fashions"]', '["Respect", "Responsibility", "Independence", "Power", "Family", "Noble Obligation"]', '["I will face any challenge to win the approval of my family", "My house''s alliance with another noble family must be sustained at all costs", "Nothing is more important than the other members of my family", "I am in love with the heir of a family that my family despises"]', '["I secretly believe that everyone is beneath me", "I hide a truly scandalous secret that would ruin my family forever", "I too often hear veiled insults and threats where none exist", "I have an insatiable desire for carnal pleasures"]', 'SCAG');