-- Add all Unearthed Arcana races in one migration (Production version)
-- These are playtest races from various UA 2021 documents

INSERT OR REPLACE INTO races (id, name, ability_score_bonuses, traits, proficiencies, languages, size, speed, source, is_unearthed_arcana) VALUES

-- Gothic Lineages
('dhampir', 'Dhampir', '{"choice": "+2 to one ability, +1 to another"}', '["Ancestral Legacy: Choose one skill proficiency and one tool proficiency or language", "Deathless Nature: No need to breathe, advantage on saves vs disease and poison, resistance to poison damage", "Spider Climb: Climbing speed equal to walking speed, can climb difficult surfaces and ceilings", "Vampiric Bite: Fangs are natural weapon (1d4 + Str/Dex piercing), can heal HP equal to damage dealt (proficiency bonus times per long rest)", "Darkvision: 60 feet"]', '[]', '["Common", "choice of one other language"]', 'Medium', 35, 'UA2021', TRUE),
('hexblood', 'Hexblood', '{"choice": "+2 to one ability, +1 to another"}', '["Ancestral Legacy: Choose one skill proficiency and one tool proficiency or language", "Fey Resilience: Advantage on saves against being charmed, magic cannot put you to sleep", "Hex Magic: Know Disguise Self and Hex spells, choose Int/Wis/Cha as spellcasting ability", "Magic Token: Create magic tokens as focus for spells, can scry through them", "Darkvision: 60 feet"]', '[]', '["Common", "choice of one other language"]', 'Medium', 30, 'UA2021', TRUE),
('reborn', 'Reborn', '{"choice": "+2 to one ability, +1 to another"}', '["Ancestral Legacy: Choose one skill proficiency and one tool proficiency or language", "Deathless Nature: No need to eat/drink/breathe/sleep, advantage on saves vs disease and poison, resistance to poison damage", "Knowledge from a Past Life: Add 1d6 to ability checks using skills (proficiency bonus times per long rest)", "Darkvision: 60 feet"]', '[]', '["Common", "choice of one other language"]', 'Medium', 30, 'UA2021', TRUE),

-- Folk of the Feywild
('fairy', 'Fairy', '{"choice": "+2 to one ability, +1 to another"}', '["Fairy Magic: Know Druidcraft cantrip, cast Faerie Fire at 3rd level, Enlarge/Reduce at 5th level (1/long rest each)", "Flight: Flying speed equal to walking speed, cannot fly if wearing medium or heavy armor", "Small Size: Can move through space of Medium or larger creature", "Darkvision: 60 feet"]', '[]', '["Common", "choice of one other language"]', 'Small', 30, 'UA2021', TRUE),
('hobgoblin-feywild', 'Hobgoblin (Feywild)', '{"constitution": 2, "intelligence": 1}', '["Fey Gift: As bonus action, give magic gift to willing creature within 5 feet (Help action, temp HP, or teleport), usable proficiency bonus times per long rest", "Fortune from the Many: When you miss attack or fail ability check or save, draw luck from allies within 30 feet to reroll", "Darkvision: 60 feet"]', '[]', '["Common", "Goblin"]', 'Medium', 30, 'UA2021', TRUE),
('owlfolk', 'Owlfolk', '{"choice": "+2 to one ability, +1 to another"}', '["Flight: Flying speed equal to walking speed, cannot fly if wearing medium or heavy armor", "Silent Feathers: Proficiency in Stealth skill", "Keen Hearing and Sight: Advantage on Perception checks that rely on hearing or sight", "Darkvision: 120 feet"]', '["Stealth"]', '["Common", "choice of one other language"]', 'Medium', 30, 'UA2021', TRUE),
('rabbitfolk', 'Rabbitfolk', '{"choice": "+2 to one ability, +1 to another"}', '["Hare-Trigger: Add proficiency bonus to initiative rolls", "Leporine Senses: Proficiency in Perception skill", "Lucky Footwork: When you fail Dexterity save, use reaction to roll 1d4 and add to save (proficiency bonus times per long rest)", "Rabbit Hop: Bonus action to jump distance equal to 5 times proficiency bonus without provoking opportunity attacks", "Darkvision: 60 feet"]', '["Perception"]', '["Common", "choice of one other language"]', 'Medium', 30, 'UA2021', TRUE),

-- Travelers of the Multiverse
('astral-elf', 'Astral Elf', '{"choice": "+2 to one ability, +1 to another"}', '["Astral Fire: Know one cantrip from cleric, druid, or wizard spell list, cast 1st level spell from same list at 3rd level (1/long rest)", "Fey Ancestry: Advantage on saves against being charmed, magic cannot put you to sleep", "Keen Senses: Proficiency in Perception skill", "Starlight Step: Teleport 30 feet as bonus action (proficiency bonus times per long rest)", "Astral Trance: 4 hours of trance instead of 8 hours sleep", "Darkvision: 60 feet"]', '["Perception"]', '["Common", "Elvish"]', 'Medium', 30, 'UA2021', TRUE),
('autognome', 'Autognome', '{"choice": "+2 to one ability, +1 to another"}', '["Armored Casing: AC 13 + Dex modifier when not wearing armor", "Built for Success: Add 1d4 to one attack roll, ability check, or save (proficiency bonus times per long rest)", "Healing Machine: Mending cantrip can target you and restore HP", "Mechanical Nature: Resistance to poison damage, immunity to disease, no need to eat/drink/breathe/sleep", "Sentry''s Rest: 6 hours of inactivity instead of 8 hours sleep", "Specialized Design: Choose one tool proficiency and one skill proficiency"]', '[]', '["Common", "choice of one other language"]', 'Small', 30, 'UA2021', TRUE),
('giff', 'Giff', '{"choice": "+2 to one ability, +1 to another"}', '["Astral Spark: Know Minor Illusion or Thaumaturgy cantrip", "Firearms Mastery: Proficiency with all firearms, ignore loading property", "Hippo Build: Count as one size larger for carrying capacity and push/drag/lift", "Damage Dealer: When you roll damage for attack with weapon, reroll any 1s (proficiency bonus times per long rest)"]', '[]', '["Common", "choice of one other language"]', 'Medium', 30, 'UA2021', TRUE),
('hadozee', 'Hadozee', '{"choice": "+2 to one ability, +1 to another"}', '["Dexterous Feet: Can use feet to manipulate objects, draw/sheathe weapons", "Glide: When falling at least 10 feet, can glide 5 feet horizontally for every 1 foot fallen", "Hadozee Dodge: When taking damage, reduce by 1d6 (proficiency bonus times per long rest)"]', '[]', '["Common", "choice of one other language"]', 'Medium', 30, 'UA2021', TRUE),
('plasmoid', 'Plasmoid', '{"choice": "+2 to one ability, +1 to another"}', '["Amorphous: Can squeeze through 1-inch wide space if not wearing/carrying anything", "Darkvision: 60 feet", "Hold Breath: Can hold breath for 1 hour", "Natural Resilience: Resistance to acid and poison damage", "Shape Self: As action, reshape body (alter height/weight, change appearance, form pseudopods)"]', '[]', '["Common", "choice of one other language"]', 'Medium', 30, 'UA2021', TRUE),
('thri-kreen', 'Thri-kreen', '{"choice": "+2 to one ability, +1 to another"}', '["Chameleon Carapace: As action, change colors for advantage on Stealth checks", "Darkvision: 60 feet", "Secondary Arms: Two secondary arms that can manipulate objects but not attack or use magic items", "Sleepless: No need to sleep, take 4 hours of inactivity to gain benefits of long rest", "Thri-kreen Telepathy: Communicate telepathically with creatures within 120 feet"]', '[]', '["Common", "choice of one other language"]', 'Medium', 30, 'UA2021', TRUE);