-- Add Unearthed Arcana backgrounds (Production version)
-- These backgrounds are from official D&D sources but not from the core rulebooks

INSERT OR REPLACE INTO backgrounds (id, name, skill_proficiencies, language_proficiencies, tool_proficiencies, equipment, feature_name, feature_description, personality_traits, ideals, bonds, flaws, source, is_unearthed_arcana) VALUES

-- Feylost
('feylost', 'Feylost', '["Deception", "Survival"]', '["One of your choice (Elvish, Gnomish, Goblin, or Sylvan)"]', '["One type of musical instrument"]', '{"items": ["musical instrument of your choice", "set of traveler''s clothes", "three trinkets from Feywild Trinkets table", "pouch"], "money": "8 gp"}', 'Feywild Connection', 'Your mannerisms and knowledge of fey customs are recognized by natives of the Feywild, who see you as one of their own. Because of this, friendly fey creatures are inclined to come to your aid if you are lost or need help in the Feywild.', '["I''m haunted by fey laughter that only I can hear, though I know it''s just my mind playing tricks on me", "Like a nomad, I can''t settle down in one place for very long", "Good music makes me weep like a baby", "Wherever I go, I try to bring a little of the warmth and tranquility of home with me"]', '["Friendship", "Honor", "Nature", "Changeability", "Power", "Escape"]', '["I would die to recover an ancient relic of my family that was lost long ago", "I will someday return to the Feywild and find the lost members of my troupe", "I know a secret about the fey that is both wondrous and terrible", "A fey has some important knowledge that I need"]', '["I easily lose track of time. My poor sense of time means I''m always late", "I think the whole multiverse is out to get me", "I''m always operating under a tight timeline, and I''m obsessed with keeping everything on schedule", "I''m a kleptomaniac who covets shiny, sparkling treasure"]', 'WBtW', TRUE),

-- Witchlight Hand
('witchlight-hand', 'Witchlight Hand', '["Performance", "Sleight of Hand"]', '["One of your choice"]', '["Disguise kit or one type of musical instrument"]', '{"items": ["disguise kit or musical instrument of your choice", "deck of cards", "carnival uniform or costume", "one trinket from Feywild Trinkets table", "pouch"], "money": "8 gp"}', 'Carnival Fixture', 'The Witchlight Carnival provides you with free, modest lodging and food. In addition, you may wander about the carnival and partake of its many wonders at no cost to you, provided you don''t disrupt its shows or cause any other trouble.', '["I''m haunted by fey laughter that only I can hear, though I know it''s just my mind playing tricks on me", "Like a nomad, I can''t settle down in one place for very long", "Good music makes me weep like a baby", "Wherever I go, I try to bring a little of the warmth and tranquility of home with me"]', '["Friendship", "Honor", "Nature", "Changeability", "Power", "Escape"]', '["I would die to recover an ancient relic of my family that was lost long ago", "The carnival is my home, and I''ll fight to protect it", "I''m loyal to a friend in the carnival", "I love the spotlight and hate being ignored"]', '["I easily lose track of time. My poor sense of time means I''m always late", "I think the whole multiverse is out to get me", "I''m always operating under a tight timeline, and I''m obsessed with keeping everything on schedule", "I''m a kleptomaniac who covets shiny, sparkling treasure"]', 'WBtW', TRUE);